=== gkmishragaurav/python_framework/python+microservice+tornado+rest/schema/address-book-v1.0.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Schema of an address book",
    "definitions": {
        "kind": {
            "type": "string",
            "enum": [
                "home",
                "work"
            ]
        },
        "address": {
            "type": "object",
            "properties": {
                "kind": {
                    "$ref": "#/definitions/kind"
                },
                "building_name": {
                    "type": "string"
                },
                "unit_number": {
                    "type": "number"
                },
                "street_number": {
                    "type": [
                        "number",
                        "string"
                    ]
                },
                "street_name": {
                    "type": "string"
                },
                "locality": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "pincode": {
                    "type": [
                        "number",
                        "string"
                    ]
                },
                "country": {
                    "type": "string"
                }
            },
            "required": [
                "kind",
                "street_name",
                "pincode",
                "country"
            ],
            "additionalProperties": false
        },
        "phone": {
            "type": "object",
            "properties": {
                "kind": {
                    "$ref": "#/definitions/kind"
                },
                "country_code": {
                    "type": "number"
                },
                "area_code": {
                    "type": "number"
                },
                "local_number": {
                    "type": "number"
                }
            },
            "required": [
                "kind",
                "country_code",
                "local_number"
            ],
            "additionalProperties": false
        },
        "email": {
            "type": "object",
            "properties": {
                "kind": {
                    "$ref": "#/definitions/kind"
                },
                "email": {
                    "type": "string",
                    "format": "email"
                }
            },
            "required": [
                "kind",
                "email"
            ],
            "additionalProperties": false
        },
        "addressEntry": {
            "$id": "#addressEntry",
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string"
                },
                "addresses": {
                    "type": "array",
                    "minItems": 0,
                    "items": {
                        "$ref": "#/definitions/address"
                    }
                },
                "phone_numbers": {
                    "type": "array",
                    "minItems": 0,
                    "items": {
                        "$ref": "#/definitions/phone"
                    }
                },
                "fax_numbers": {
                    "type": "array",
                    "minItems": 0,
                    "items": {
                        "$ref": "#/definitions/phone"
                    }
                },
                "emails": {
                    "type": "array",
                    "minItems": 0,
                    "items": {
                        "$ref": "#/definitions/email"
                    }
                }
            },
            "required": [
                "full_name"
            ],
            "additionalProperties": false
        }
    },
    "$ref": "#/definitions/addressEntry"
}

=== gkmishragaurav/python_framework/python+microservice+tornado+rest/data/addresses/raga.json
{
    "full_name": "Rahul Gandhi",
    "addresses": [
        {
            "kind": "work",
            "building_name": "Indian National Congress Office",
            "street_number": 24,
            "street_name": "Akbar Rd",
            "city": "New Delhi",
            "pincode": 110011,
            "country": "India"
        },
        {
            "kind": "home",
            "street_number": 12,
            "street_name": "Tughlak Lane",
            "city": "New Delhi",
            "pincode": 110011,
            "country": "India"
        }
    ],
    "phone_numbers": [
        {
            "kind": "work",
            "country_code": 91,
            "area_code": 11,
            "local_number": 23795161
        }
    ],
    "fax_numbers": [
        {
            "kind": "work",
            "country_code": 91,
            "area_code": 11,
            "local_number": 23012410
        }
    ],
    "emails": [
        {
            "kind": "work",
            "email": "office@rahulgandhi.in"
        }
    ]
}

=== gkmishragaurav/python_framework/python+microservice+tornado+rest/data/addresses/namo.json
{
    "full_name": "Narendra Modi",
    "addresses": [
        {
            "kind": "work",
            "building_name": "Prime Ministerâ€™s Office",
            "street_name": "South Block",
            "locality": "Raisina Hill",
            "city": "New Delhi",
            "pincode": 110011,
            "country": "India"
        },
        {
            "kind": "work",
            "building_name": "BJP Jansampark Karyalaya",
            "street_number": 77,
            "street_name": "Ravindrapuri Rd",
            "locality": "Bhelupur",
            "city": "Varanasi",
            "province": "Uttar Pradesh",
            "pincode": 221005,
            "country": "India"
        },
        {
            "kind": "home",
            "street_number": 7,
            "street_name": "Race Course Road",
            "city": "New Delhi",
            "pincode": 110061,
            "country": "India"
        }
    ],
    "phone_numbers": [
        {
            "kind": "work",
            "country_code": 91,
            "area_code": 11,
            "local_number": 23012312
        }
    ],
    "fax_numbers": [
        {
            "kind": "work",
            "country_code": 91,
            "area_code": 11,
            "local_number": 23019545
        },
        {
            "kind": "work",
            "country_code": 91,
            "area_code": 11,
            "local_number": 23016857
        }
    ],
    "emails": [
        {
            "kind": "work",
            "email": "connect@mygov.nic.in"
        },
        {
            "kind": "home",
            "email": "narendramodi1234@gmail.com"
        }
    ]
}
